#!/usr/bin/env bash

set -x

# ====== Variables =============================

declare -A gaps
declare -A color

gaps["top"]="8"
gaps["bottom"]="8"
gaps["left"]="8"
gaps["right"]="8"
gaps["inner"]="8"

color["focused"]="0xE0808080"
color["normal"]="0x00010101"
color["preselect"]="0xE02d74da"

# Uncomment to refresh ubersicht widget on workspace change
# Make sure to replace WIDGET NAME for the name of the ubersicht widget
#ubersicht_spaces_refresh_command="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"WIDGET NAME\"'"

# ===== Loading Scripting Additions ============

# See: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#macos-big-sur---automatically-load-scripting-addition-on-startup
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa


function setup_space {
    local idx="$1"
    local name="$2"
    local space=
    echo "setup space $idx : $name"

    space=$(yabai -m query --spaces --space "$idx")
    if [ -z "$space" ]; then
        yabai -m space --create
    fi

    yabai -m space "$idx" --label "$name"
}

setup_space 1 one
setup_space 2 two
setup_space 3 three
setup_space 4 four
setup_space 5 five
setup_space 6 six
setup_space 7 seven
setup_space 8 eight
setup_space 9 nine
setup_space 10 ten

# ===== Tiling setting =========================
yabai -m config layout                      bsp

yabai -m config top_padding                 "${gaps["top"]}"
yabai -m config bottom_padding              "${gaps["bottom"]}"
yabai -m config left_padding                "${gaps["left"]}"
yabai -m config right_padding               "${gaps["right"]}"
yabai -m config window_gap                  "${gaps["inner"]}"

yabai -m config mouse_follows_focus         on
yabai -m config focus_follows_mouse         on

yabai -m config window_topmost              off
yabai -m config window_opacity              off
yabai -m config window_shadow               float

yabai -m config window_border               off
yabai -m config window_border_blur          off
yabai -m config window_border_width         2
yabai -m config active_window_border_color  "${color["focused"]}"
yabai -m config normal_window_border_color  "${color["normal"]}"
yabai -m config insert_feedback_color       "${color["preselect"]}"

yabai -m config active_window_opacity       1.0
yabai -m config normal_window_opacity       0.90
yabai -m config split_ratio                 0.50

yabai -m config auto_balance                off

yabai -m config mouse_modifier              alt
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize

yabai -m mouse_drop_action                  swap

# ===== Rules ==================================

yabai -m rule --add label="Finder" app="^Finder$" sticky=on manage=off grid=6:6:1:1:4:4;
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off sticky=on grid=4:4:1:1:2:2
yabai -m rule --add label="macfeh" app="^macfeh$" manage=off grid=4:4:1:1:2:2
yabai -m rule --add label="System Preferences" app="^System Preferences$" title=".*" manage=off grid=6:6:1:1:4:4
yabai -m rule --add label="App Store" app="^App Store$" manage=off grid=6:6:1:1:4:4
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off grid=4:4:1:1:2:2
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off sticky=on grid=4:4:1:1:2:2
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off grid=4:4:1:1:2:2
yabai -m rule --add label="mpv" app="^mpv$" manage=off grid=4:4:1:1:2:2
yabai -m rule --add label="Software Update" title="Software Update" manage=off grid=4:4:1:1:2:2
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off grid=4:4:1:1:2:2

yabai -m rule --add app="^System Settings$" sticky=on layer=above manage=off grid=6:6:1:1:4:4;
yabai -m rule --add app="^Alfred Preferences$" sticky=on layer=above manage=off grid=4:4:1:1:2:2;
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off grid=4:4:1:1:2:2;
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off grid=6:6:1:1:4:4;
yabai -m rule --add app="^1Password$" layer=above manage=off grid=6:6:3:0:4:4;
yabai -m rule --add label="Pritunl" app="Pritunl" sticky=on layer=above manage=off grid=4:4:1:1:2:2;
qabai -m rule --add label="MAMP" app="MAMP" sticky=on layer=above manage=off grid=4:4:1:1:2:2;


yabai -m rule --add app="^Chrome$" space=1
yabai -m rule --add app="^Safari$" space=1
yabai -m rule --add app="^FireFox$" space=1

yabai -m rule --add app="iTerm2$" space=2
yabai -m rule --add app="Warp$" space=2

yabai -m rule --add app="^Figma$" space=4

yabai -m rule --add app="^Sublime Merge$" space=6

yabai -m rule --add app="^Spotify$" space=9
yabai -m rule --add app="^Calendar$" space=9
yabai -m rule --add app="Cron" space=9

yabai -m rule --add app="^Slack$" space=10
yabai -m rule --add app="^Mattermost$" space=10
yabai -m rule --add app="^Telegram$" space=10
yabai -m rule --add app="^Skype$" space=10 

# ===== Signals ================================

yabai -m signal --add event=application_front_switched action="${ubersicht_spaces_refresh_command}"
yabai -m signal --add event=display_changed action="${ubersicht_spaces_refresh_command}"
yabai -m signal --add event=space_changed action="${ubersicht_spaces_refresh_command}"
yabai -m signal --add event=window_created action="${ubersicht_spaces_refresh_command}"
yabai -m signal --add event=window_destroyed action="${ubersicht_spaces_refresh_command}"
yabai -m signal --add event=window_focused action="${ubersicht_spaces_refresh_command}"
yabai -m signal --add event=window_title_changed action="${ubersicht_spaces_refresh_command}"

set +x
printf "yabai: configuration loaded...\\n"
